<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>fileTypes</key>
    <array>
        <string>yak</string>
    </array>
    <key>name</key>
    <string>Yak</string>
    <key>scopeName</key>
    <string>source.yak</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>include</key>
            <string>#comment</string>
        </dict>
        <dict>
            <key>match</key>
            <string>#.*</string>
            <key>name</key>
            <string>comment.line.yak</string>
        </dict>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>keyword.yak</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>meta.variable.yak</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>meta.delimited.yak</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>meta.variable.yak</string>
                </dict>
                <key>5</key>
                <dict>
                    <key>name</key>
                    <string>keyword.operator.yak</string>
                </dict>
                <key>6</key>
                <dict>
                    <key>name</key>
                    <string>meta.brace.curly.yak</string>
                </dict>
            </dict>
            <key>match</key>
            <string>^\s*(?:(instance|exports)|([\w\-+*/%^$&lt;&gt;=?!]+))(?:\s*(\.|::)([\w\-+*/%^$&lt;&gt;=?!]+))*\s+(\|?:?=)\s*(\{|$)</string>
            <key>name</key>
            <string>meta.named-funject.yak</string>
        </dict>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>keyword.yak</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>meta.variable.yak</string>
                </dict>
            </dict>
            <key>match</key>
            <string>^\s*(class|module)\s+([\w\-+*/%^$&lt;&gt;=?!]+)</string>
            <key>name</key>
            <string>meta.named-class.yak</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?&lt;![\w\-+*/%^$&lt;&gt;=?!])-?(\d*\.)?\d+(e[-+]?\d+)?(?![\w\-+*/%^$&lt;&gt;=?!])</string>
            <key>name</key>
            <string>constant.numeric.yak</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?&lt;![\w\-+*/%^$&lt;&gt;=?!])(true|false|nil|unknown)(?![\w\-+*/%^$&lt;&gt;=?!])</string>
            <key>name</key>
            <string>constant.yak</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?&lt;![\w\-+*/%^$&lt;&gt;=?!])(super|exports|instance)(?![\w\-+*/%^$&lt;&gt;=?!])</string>
            <key>name</key>
            <string>keyword.yak</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?&lt;![\w\-+*/%^$&lt;&gt;=?!])(and|or|not|is|isnt|\|?:?=|&lt;&lt;|&lt;-|[=!&lt;&gt;]=|[&lt;&gt;\-+/*%^])(?![\w\-+*/%^$&lt;&gt;=?!])</string>
            <key>name</key>
            <string>keyword.operator.yak</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?&lt;![\w\-+*/%^$&lt;&gt;=?!])(error|print|by)(?![\w\-+*/%^$&lt;&gt;=?!])</string>
            <key>name</key>
            <string>support.function.yak</string>
        </dict>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>meta.delimiter.period.yak</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>support.function.yak</string>
                </dict>
            </dict>
            <key>match</key>
            <string>(\.|::)(new|instance|on|symbol\?|number\?|string\?|boolean?list\?|nil\?|unknown\?|to-string|inspect|sqrt|ln|log|sin|cos|tan|sec|csc|cot|asin|acos|atan|abs|ceil|floor|round|times|and|or|not|length|contains?|index-of|split|replace|replace-all|empty\?)(?![\w\-+*/%^$&lt;&gt;=?!])</string>
        </dict>
        <dict>
            <key>match</key>
            <string>,</string>
            <key>name</key>
            <string>meta.delimiter.comma.yak</string>
        </dict>
        <dict>
            <key>match</key>
            <string>::</string>
            <key>name</key>
            <string>meta.delimiter.colon.yak</string>
        </dict>
        <dict>
            <key>match</key>
            <string>:</string>
            <key>name</key>
            <string>keyword.operator.yak</string>
        </dict>
        <dict>
            <key>match</key>
            <string>[{}]</string>
            <key>name</key>
            <string>meta.brace.curly.yak</string>
        </dict>
        <dict>
            <key>match</key>
            <string>[()]</string>
            <key>name</key>
            <string>meta.brace.round.yak</string>
        </dict>
        <dict>
            <key>match</key>
            <string>[\[\]]</string>
            <key>name</key>
            <string>meta.brace.square.yak</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(\.)([\w\-+*/%^$&lt;&gt;=?!]+)</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>meta.delimiter.period.yak</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>symbol.yak</string>
                </dict>
            </dict>
        </dict>
        <dict>
            <key>match</key>
            <string>@[\w\-+*/%^$&lt;&gt;=?!]+</string>
            <key>name</key>
            <string>variable.parameter.yak</string>
        </dict>
        <dict>
            <key>match</key>
            <string>[\w\-+*/%^$&lt;&gt;=?!]+</string>
            <key>name</key>
            <string>meta.variable.yak</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>'</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.begin.yak</string>
                </dict>
            </dict>
            <key>end</key>
            <string>'</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.end.yak</string>
                </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.single.yak</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>\\[\\'"nrt]</string>
                    <key>name</key>
                    <string>constant.character.escape.yak</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>begin</key>
            <string>"</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.begin.yak</string>
                </dict>
            </dict>
            <key>end</key>
            <string>"</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.end.yak</string>
                </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.single.yak</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>\\[\\'"nrt]</string>
                    <key>name</key>
                    <string>constant.character.escape.yak</string>
                </dict>
            </array>
        </dict>
    </array>
    <key>repository</key>
    <dict>
        <key>comment</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>begin</key>
                    <string>#\|</string>
                    <key>end</key>
                    <string>\|#</string>
                    <key>name</key>
                    <string>comment.multiline.yak</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#comment</string>
                        </dict>
                    </array>
                </dict>
            </array>
        </dict>
    </dict>
</dict>
</plist>
