<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>fileTypes</key>
    <array>
        <string>yak</string>
    </array>
    <key>name</key>
    <string>Yak</string>
    <key>scopeName</key>
    <string>source.yak</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>include</key>
            <string>#comment</string>
        </dict>
        <dict>
            <key>match</key>
            <string>#.+</string>
            <key>name</key>
            <string>comment.line.yak</string>
        </dict>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>variable.yak</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>keyword.operator.yak</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>meta.brace.curly.yak</string>
                </dict>
            </dict>
            <key>match</key>
            <string>^\s*([\w=?\-]+)\s*(\|?\:?=)\s*(\{|$)</string>
            <key>name</key>
            <string>meta.named-funject.yak</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\b(\d*\.)?\d+(e[-+]?\d+)?(?![\w=?\-])</string>
            <key>name</key>
            <string>constant.numeric.yak</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\b(true|false|nil|dot|unknown)\b</string>
            <key>name</key>
            <string>keyword.yak</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\b(error|print)\b</string>
            <key>name</key>
            <string>support.constant.yak</string>
        </dict>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>meta.delimiter.period.yak</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>support.constant.yak</string>
                </dict>
            </dict>
            <key>match</key>
            <string>(\.)(equals|plus|minus|times|div)\b</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\.</string>
            <key>name</key>
            <string>meta.delimiter.period.yak</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\,</string>
            <key>name</key>
            <string>meta.delimiter.comma.yak</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\:</string>
            <key>name</key>
            <string>meta.delimiter.comma.yak</string>
        </dict>
        <dict>
            <key>match</key>
            <string>[{}]</string>
            <key>name</key>
            <string>meta.brace.curly.yak</string>
        </dict>
        <dict>
            <key>match</key>
            <string>[()]</string>
            <key>name</key>
            <string>meta.brace.round.yak</string>
        </dict>
        <dict>
            <key>match</key>
            <string>[\[\]]</string>
            <key>name</key>
            <string>meta.brace.square.yak</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\.</string>
            <key>name</key>
            <string>meta.brace.square.yak</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\|?\:?=|&lt;&lt;|&lt;-</string>
            <key>name</key>
            <string>keyword.operator.yak</string>
        </dict>
        <dict>
            <key>match</key>
            <string>@[\w_=?\-]+</string>
            <key>name</key>
            <string>constant.function.parameter.yak</string>
        </dict>
        <dict>
            <key>match</key>
            <string>[\w=?\-]+</string>
            <key>name</key>
            <string>variable.yak</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>'</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.begin.yak</string>
                </dict>
            </dict>
            <key>end</key>
            <string>'</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.end.yak</string>
                </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.single.yak</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>\\[\\'"nrt]</string>
                    <key>name</key>
                    <string>constant.character.escape.yak</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>begin</key>
            <string>"</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.begin.yak</string>
                </dict>
            </dict>
            <key>end</key>
            <string>"</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.end.yak</string>
                </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.single.yak</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>\\[\\'"nrt]</string>
                    <key>name</key>
                    <string>constant.character.escape.yak</string>
                </dict>
            </array>
        </dict>
    </array>
    <key>repository</key>
    <dict>
        <key>comment</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>begin</key>
                    <string>#\|</string>
                    <key>end</key>
                    <string>\|#</string>
                    <key>name</key>
                    <string>comment.multiline.yak</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#comment</string>
                        </dict>
                    </array>
                </dict>
            </array>
        </dict>
    </dict>
</dict>
</plist>
